spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:grade_tool_server_test;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false